version: '3.7'

services:

  mongo:
    image: mongo:5.0
    container_name: sku_mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=user
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - volume_sku_mongo:/data/db
    ports:
      - "27017:27017"
    networks:
      default:

volumes:
  volume_sku_mongo:

networks:
  default: